### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by sharplet** [sharplet/Regex#12]
So, some day it looks like `NSRegularExpression` _will_ be ported to Linux. \o/

At the time of writing, the implementation is stubbed out and throws a runtime error: https://github.com/apple/swift-corelibs-foundation/blob/0254bc20d453626494d0e51d0cae35cc61ee3e46/Foundation/NSRegularExpression.swift.

~~Theoretically this should mean that you can compile and link against Regex on Linux, but when I tested it I got some linker errors. For now, I've filed a bug here: https://bugs.swift.org/browse/SR-82.~~

**Comment by andrew804** [comment]
I have made some changes and have successfully complied on Linux. The main differences are:

- NSRegularExpression is called RegularExpression
- NSTextCheckingResult is called TextCheckingResult
- func rangeAt:index is called range:atIndex

My solution uses complier conditional code i.e. `#if os(Linux)` which I have added onto the existing complier conditional statements that check for the swift version.

I will submit a pull request shortly.

**Comment by sharplet** [comment]
https://github.com/sharplet/Regex/pull/43 should basically be ready for Linux now (even though the build is currently failing).

**Comment by andrew804** [comment]
Didn't see #43. Thats great. Most things seem to be there but I have submitted my pull request anyway.

**Comment by sharplet** [comment]
Done in #44.
