### ISSUE TITLE
Regex isn't on CocoaPods trunk

### ISSUE THREAD

**Issue by sharplet** [sharplet/Regex#13]
- You can still use Regex directly in your Podfile, which is great;
- BUT, you can't yet transitively depend on Regex from another pod.

Long-term, I've started discussions with the author of https://github.com/brynbellomy/Regex about the possibility of merging the two projects.

Short-term, I can currently think of two options:
- Just prefix the podspec and push it to Trunk. The _project_ would still be called Regex officially, but the _pod_ would be named something like `STRegex`. This would be pretty simple, though still potentially quite confusing for users.
- Maintain a spec repo dedicated to Regex and ask users to specify a custom `source` in their Podfile. However I don't believe this solves the namespace collision problem with the master spec repo. I'd like to investigate this further.

**Comment by Ashton-W** [comment]
Get it on Trunk, one way or another

**Comment by sharplet** [comment]
https://twitter.com/CocoaPodsFeed/status/674008133107367937
