### ISSUE TITLE
Regex shouldn't be StringLitteralConvertible

### ISSUE THREAD

**Issue by fpillet** [sharplet/Regex#21]
As convenient as this may seem, Regex should not be a `StringLiteralConvertible`.

Consider this code:

``` swift
func crasher(s: String) {
    switch s {
    case "*starred*":
         print("starred")
    case "any":
         print("any")
    default:
        print("unknown")
    }
}
```

Calling the crasher function crashes the app. Why? Because the case string is being silently converted to a `Regex` instance by the way of its `StringLiteralConvertible` initializer!

In other words, simply using Regex in an application silently turns all `case` string tests into `Regex` instances.

This has two drawbacks:
- it hampers performance when not needed
- it risks crashing the application, like in the example above, because the string is not a valid regex.

Moreover, your example correctly shows a correct `case` statement using an explicit `Regex` instance.

Simply removing conformance to the `StringLiteralConvertible` protocol will fix this issue.

Thanks for a nice µframework!

**Comment by sharplet** [comment]
> In other words, simply using Regex in an application silently turns all case string tests into Regex instances.
> 
> ...
> 
> Simply removing conformance to the StringLiteralConvertible protocol will fix this issue.

Totally. So if you take code that's otherwise fine then simply add `import Regex`, you've magically turned your code into a crash bug. I agree, this is not good.

I think I'd be willing to accept a PR removing the `StringLiteralConvertible` conformance. I'm already planning to bump to 0.3 for the next release because of the other breaking change to the type of `MatchResult.captures`.

> Thanks for a nice µframework!

You're welcome!

**Comment by sharplet** [comment]
Ok, so I've been trying to reproduce this in a test case, but haven't been able to reproduce the crash yet.

Would you minding sharing some code that causes the crash for you? Your example doesn't compile.

**Comment by fpillet** [comment]
I have updated my example, it was lacking a switch statement (retyped the code as mine is actually a bit different)

**Comment by fpillet** [comment]
Note that it crashes because `"*starred*"` is not a valid initializer string for `Regex`.
