### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by sharplet** [sharplet/Regex#25]
This one would be great place to start for anyone looking to make a contribution.

See http://keepachangelog.com/ for the format I'd like to use.

I've been keeping an informal changelog in the [release notes](/sharplet/Regex/releases), so that would probably be a great place too start. I'd like the changelog to retroactively cover all existing releases, and then CONTRIBUTING.md can be updated to request that the changelog be updated with each pull request.

**Comment by ninjaprawn** [comment]
Wouldn't it be better to create a CHANGELOG.md to keep track of changes (https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md)? 

This way, you can reference the changes (afaik) when you release a new version.

**Comment by sharplet** [comment]
After some more thought on this, I'd prefer not to have to maintain the changelog in two places.
