### ISSUE TITLE
NSRegularExpressionOptions?

### ISSUE THREAD

**Issue by sharplet** [sharplet/Regex#3]
I'm personally fairly happy with the defaults, but if there's enough demand for some options it would be good to look into.

Case (in)sensitivity is one consideration.

**Comment by leotumwattana** [comment]
+1 for case (in)sensitivity

**Comment by sharplet** [comment]
Awesome. Are you interested in submitting a PR?

I've been thinking a little about the API—here's what I've come up with, for posterity.

I think this kind of thing is probably the most obvious:

``` swift
Regex("foo", caseSensitive: false)
Regex("foo", ignoreCase: true)
Regex("foo", options: [.IgnoreCase])
```

It has the downside of being a little wordy though.

I'm not entirely opposed to using PCRE style options, specified as a second string:

``` swift
Regex("foo", "i") // => /foo/i
```

It's not as user-friendly, but it's pretty standard these days, and I think the added brevity could be really nice.

**Comment by gfontenot** [comment]
I vote for `Regex("foo", options: [.IgnoreCase])`. Seems like it's a nice compromise between verbosity, flexibility, and ease of use.

**Comment by mokagio** [comment]
I'm on the `Regex("pizza", options: [.IgnoreCase])` wagon too, in particular for the flexibility.
