### ISSUE TITLE
Regex.matches does not exist

### ISSUE THREAD

**Issue by ricardopereira** [sharplet/Regex#30]
I was testing the Regex object and the README has an example using `matches` but it does not exist.

``` swift
Regex("Custom from:([0-9]+) to:([0-9]+)").matches(value) //error
```

Another thing, is it normal the first capture to be the full value?

``` swift
let matchResult = Regex("Custom from:([0-9]+) to:([0-9]+)").match(value)
// value e.g.: Custom from:1451811437 to:1452329837

print(matchResult.captures.count) //prints 3
print(matchResult.captures[0]) //prints Custom from:1451811437 to:1452329837
print(matchResult.captures[1]) //prints 1451811437
print(matchResult.captures[2]) //prints 1452329837
```

**Comment by sharplet** [comment]
Hi @ricardopereira!

What version of Regex do you have installed / how did you install it?

I just tried to reproduce this, but wasn't successful. Everything seemed to work as expected with this test case (which I've pushed to [this branch](https://github.com/sharplet/Regex/blob/test-issue-30/Tests/Issue30Spec.swift)):

``` swift
final class Issue30Spec: QuickSpec {
  override func spec() {

    let regex = Regex("Custom from:([0-9]+) to:([0-9]+)")
    let value = "Custom from:1451811437 to:1452329837"

    it("matches") {
      expect(regex.matches(value)).to(beTrue())
    }

    it("captures as expected") {
      let captures = regex.match(value)!.captures
      expect(captures.count).to(equal(2))
      expect(captures.flatMap { $0 }).to(equal(["1451811437", "1452329837"]))
    }

  }
}

import Quick
import Nimble
import Regex
```

Also, you said you get an error:

> ```
> Regex("Custom from:([0-9]+) to:([0-9]+)").matches(value) //error
> ```

What was the error message?

**Comment by ricardopereira** [comment]
Wow, I am using `0.3.0` but I noticed that the `Pods/Regex/Regex.swift` is different from your tag `0.3.0`.

```
//
//  Regex.swift
//  Regex
//
//  Created by bryn austin bellomy on 2/10/2015
//  Copyright (c) 2015 bryn austin bellomy. All rights reserved.
//
...
```

Is that you: `bryn austin`? 😬

My `podfile`

```
platform :ios, '8.0'
use_frameworks!

target 'Money' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Regex'
end
```

**Comment by ricardopereira** [comment]
Sorry, I am so stupid.
The pod is `STRegex` :facepalm:

**Comment by sharplet** [comment]
You're not stupid, it's certainly not ideal that the pod has a different name!
