### ISSUE TITLE
Cocoapod support for :git

### ISSUE THREAD

**Issue by jdbroadb** [sharplet/Regex#40]
Using the :git tag in a podfile does not work. Receive the following errors in command line of git update:

```
fatal: No names found, cannot describe anything.

[!] Unable to satisfy the following requirements:

  - `STRegex (from `https://github.com/sharplet/Regex.git`)` required by `Podfile`

```

**Comment by sharplet** [comment]
Is this still an issue?

I just tested this with the following Podfile, and everything worked as expected:

``` ruby
use_frameworks!

target "RegexTest" do
  pod "STRegex", git: "https://github.com/sharplet/Regex.git"
end
```

**Comment by sharplet** [comment]
Closing for now, but if this is still an issue please let me know.
