### ISSUE TITLE
Module compiled with Swift 2.3 cannot be imported in Swift 3

### ISSUE THREAD

**Issue by bitomule** [sharplet/Regex#45]
I get this error trying to use Regex with Carthage. Any ideas?

**Comment by sharplet** [comment]
Could you try re-running Carthage with `--toolchain com.apple.dt.toolchain.XcodeDefault`?

**Comment by bitomule** [comment]
I tried using swift-3 branch and worked. Thought it was already merged in master.

**Comment by sharplet** [comment]
The master branch is source-compatible with Swift 3, but will compile for Swift 2.3 by default when used with Carthage. The swift-3 branch is a breaking change, and I'd like to tag a new release with the changes there soon.

**Comment by sharplet** [comment]
FWIW, I just tested and with `--toolchain com.apple.dt.toolchain.XcodeDefault` it does compile successfully on master.

**Comment by sharplet** [comment]
I'm going to close this for now, but please let me know if you experience any more Xcode compatibility issues.

FYI, I also just [tagged 1.0.0](https://github.com/sharplet/Regex/releases/tag/1.0.0) with support for Swift 3.1, 3.2 and 4.0 (inc. both Linux and Xcode 8 & 9).
