### ISSUE TITLE
Swift PM Intergration

### ISSUE THREAD

**Issue by OdNairy** [sharplet/Regex#46]
Cannot import Regex into my project.
`swift package update` command tells me:  
`error: the package has an unsupported layout, unexpected source file(s) found: /blablabla/Packages/Regex-0.3.1/Tests/OptionsSpec.swift,
/blablabla/Packages/Regex-0.3.1/Tests/RegexSpec.swift,   
/blablabla/Packages/Regex-0.3.1/Tests/StringReplacementSpec.swift
fix: move the file(s) inside a module`

**Comment by sharplet** [comment]
Thanks for reporting this. I think these days swiftpm expects tests for a module to be in the folder `Tests/<module>Tests`. Would you be interested in contributing a PR with a fix?

**Comment by andrew804** [comment]
How long does the Travis CI build usually take to complete?

**Comment by sharplet** [comment]
Closed by #47.

**Comment by sharplet** [comment]
I've just pushed https://github.com/sharplet/Regex/releases/tag/0.4.3 with the fix.
