### ISSUE TITLE
Doesn't support swift 4.2

### ISSUE THREAD

**Issue by vi4m** [sharplet/Regex#62]
Package.swift manifest is not compatible with Swift 4.2 - failing during compilation. Any plans for upgrading?

```sh
/var/folders/g1/h5w4d87x1cd4thjntw7l19rjw60qhj/T/TemporaryFile.IusUyX.swift:14:27: error: cannot convert value of type 'Int' to expected element type 'SwiftVersion'
  swiftLanguageVersions: [3, 4]
```

More info: https://github.com/apple/swift-evolution/blob/master/proposals/0209-package-manager-swift-lang-version-update.md

**Comment by sharplet** [comment]
Thanks for the report! Could you please share your `Package.swift` & `Package.resolved` files, and the output of `swift --version` and `xcodebuild -version` (if applicable)?

**Comment by sharplet** [comment]
I’ve just released [Regex 2](https://github.com/sharplet/Regex/releases/tag/2.0.0), let me know if you have any more issues!
