### ISSUE TITLE
Not available with Carthage and Xcode 10.2

### ISSUE THREAD

**Issue by iby** [sharplet/Regex#64]
```
error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'Regex-OSX')
```

☹️

**Comment by emirandm** [comment]
also for other targets iOS/tvOS

**Comment by mohpor** [comment]
@all

You can use my fork for now:
```ruby
...
pod 'STRegex', :git => 'https://github.com/mohpor/Regex.git'
...
```

**Comment by ricardopereira** [comment]
@sharplet Any chance to release a new version with Swift 5 (Xcode 10.2) support?

**Comment by sharplet** [comment]
Sorry for the radio silence folks, I'll try take a look this week!

**Comment by sharplet** [comment]
I’ve just released [Regex 2](https://github.com/sharplet/Regex/releases/tag/2.0.0), let me know if there’s any more issues!

**Comment by ricardopereira** [comment]
@sharplet Yeah 🙌 Thank you.
