### ISSUE TITLE
UTF16View

### ISSUE THREAD

**Issue by davidbjames** [sharplet/Regex#67]
Hi,

First off, I love this library and use it all the time. Great job! Also good to see recent maintenance!

This morning, I was reading a post about Swift 5 strings and noticed a comment about using UTF8View instead of UTF16View in some cases: https://swift.org/blog/utf8-string/#impact-on-existing-code

MatchResult.swift uses UTF16View in several places. Is this something that should be refactored per the article? 

Respectfully,
David

**Comment by sharplet** [comment]
@davidbjames Thank you, I’m really glad you’re finding it useful!

I think you’re right that it would be worth revisiting how we’re mapping between index types internally, I’ll take a look.
