### ISSUE TITLE
public struct Options has generic name that cannot be disambiguated

### ISSUE THREAD

**Issue by jpmhouston** [sharplet/Regex#73]
Because of `Regex` is both the name of the struct and the module, then as discussed in Swift bug SR-5304 Regex's `struct Option` cannot be disambiguated using `Regex.Options`. Method to workaround this issue are less than ideal https://stackoverflow.com/a/38508385/592739

Renaming either the module or the struct would break existing code. Would it be terrible to rename `Options` to something like `RegexOptions`. Or instead adding a public typealias `RegexOptions = Options` might work.

**Comment by sharplet** [comment]
Thanks for raising this!

I think nesting `Options` inside `Regex` would make a lot of sense. We could then add `public typealias Options = Regex.Options`, and hopefully even include a deprecation warning that it will be removed in a future release.

Would you be interested in opening a pull request to that effect?
